markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
title: iwisunny's github page
description: iwisunny's Blog, powered by Jekyll...

author: iwisunny

seo: 
  keyword: 
  description: 
config:
  js_dir:
  img_dir:
  css_dir:
